### ISSUE TITLE
Functional improvements to Line

### ISSUE THREAD

**Issue by ebebbington** [drashland/line#11]
### Discussed in https://github.com/drashland/line/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **kinghat** July 22, 2021</sup>
i see there are some additions in the pipeline but maybe we could discuss a few more here?

1. ability to add short names to passed options/flags like `-a` for `--all` or `-l` for `--long`.
2. when passing `--long` it would need a value for the `getOptionValue` call but sometimes options dont need a value and the option being passed is enough.
3. being able to get help on an option on a subcommand or the subcommand itself when the subcommand has logic with or without passing args or options. in that case, passing `-h` would halt the logic and present you the help of args and options for that subcommand.</div>

**Comment by crookse** [comment]
hey @kinghat, i think you already saw this, but just wanted to make sure since you raised the discussion. we added the features to support short names, long names, and options WITH and WITHOUT values

**Comment by kinghat** [comment]
> hey @kinghat, i think you already saw this, but just wanted to make sure since you raised the discussion. we added the features to support short names, long names, and options WITH and WITHOUT values

thanks for the big update! cool to see all new code you guys have dropped. I will be updating my line tool in the next couple weeks so if I notice anything, I'll report back 🙏
