### ISSUE TITLE
Support just a main command

### ISSUE THREAD

**Issue by crookse** [drashland/line#5]
## Summary

What:

Add support for just a main command that doesn't require subcommands. This should be able to have options as well.

Why:

A user in the discord help channel raised the issue and its a legit use case in my opinion. 

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Write documentation
- [ ] Write unit tests
- [ ] Write integration tests

**Comment by ebebbington** [comment]
Just to expand upon this, an example of a CLI built like this would be similar to the `cat` command, where there’s no sub commands, just a main command, options and args
